[build]
builder = "dockerfile"

[deploy]
startCommand = "RUST_LOG=info,nostr_rs_relay=info ./nostr-rs-relay"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[[services]]
